---
# The name of our application (machine-readable)
app_name: testapp

# Users that will administrate and deploy the application
appuser_username: appuser
admin_username: appadmin

# Passwords for created users
admin_password:   "{{ vault_appadmin_password }}"
appuser_password: "{{ vault_appuser_password }}"

# Database configuration
database_root_password: "{{ vault_database_root_password }}"
database_name: testapp
database_username: testappdbuser
database_password: "{{ vault_database_password }}" 

# Your local public key, e.g. ~/.ssh/id_rsa.pub which is added to the
# "authorized_keys" file on every server allowing SSH access
# $ cat ~/.ssh/id_rsa.pub | pbcopy
local_authorized_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAe74npmzsUje13qWonJeYuQubxUeGArOXAu0rYbZfqcs5+1oY3jAXQDOjHSai4RpXsLkIyE11KgUdIuOYehXPCMtA03fRFvywuyhHbLeA1SATYzxlqm6JscPyVU6nfWu/6GWFTrVB9SjffQ35TM1gPqxL7zLCnVJIM4Dzke8y1a7h0yLlTwhdWXfVWqayPnB0k/drZ28lQTxLCQE92yWvKKtaxfLlejUIOBG/y7hJfg5+Ff7zIsr5+48Fy9do0piwEBaiXpe/qsi5E7GSDxm2ZEq8TLJ4nENBssjqovl0Yi0J6cEeNiDAnEwOurXT4lW3mf1crs7fBuOD+GDpYRCKhEQBrNGCzQpd0YFdtA6l7lWh9lBhwI3qI6tNGm8CP5MlBnuvx/ximik1UQ9dBezL+d11La3akLSDGb+u3hpvMa0Gfi0bEvOrCtsH+i0FIiohtp7bR/wvpF273N+AK/NDcpnhnpZG+e98vR1eTtRs3jYinfGl/QExL677VrFujguf4DxtRuo5C0ppRSQBRCdGDiYmcrTtghfkb7F5RfI7rv1+ZZ4WOCc0tUTUGvvx8CVekffr4gc5gXNA8+Q8Sr0s5GN7/Rk4cC3TY3/ItVH9OvYAra0xZbZO0NKu+6L7EbBIc7si7Nr21LmJBCjeTIfds1L5zXLfn47vSD/R3Ep2mw== luke@lukeroberts.me

# Generate a GitHub access token for Composer
# https://help.github.com/articles/creating-an-access-token-for-command-line-use/
github_token: "{{ vault_github_token }}" 
