---
# Not strictly necessary, but useful to outline the difference
# between deb.yml and rpm.yml in this case. No SELinux.
- name: Create Persistent Dir
  file:
    path: '/home/{{ appuser_username }}/{{ app_name }}/persist'
    recurse: yes
    state: directory
    owner: '{{ appuser_username }}'
    group: '{{ appuser_username }}'