---
# Create Directory where our app/website will live
- name: Create App Directory
  file:
    path: '/home/{{ appuser_username }}/{{ app_name }}'
    recurse: yes
    state: directory
    owner: '{{ appuser_username }}'
    group: '{{ appuser_username }}'

# Composer Directory
- name: Ensure user has .composer directory
  file:
    path: '/home/{{ appuser_username }}/.composer'
    state: directory
    owner: '{{ appuser_username }}'
    group: '{{ appuser_username }}'
