---
- name: Add PHP PPA Repository
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present

- name: Update apt packages
  apt:
    update_cache: yes

- name: Install PHP
  apt:
    pkg: "{{ php_version }}"
    state: latest

- name: Install PHP-FPM
  apt:
    pkg: "{{ php_version }}-fpm"
    state: latest

- name: Install PHP Packages
  with_items: php.packages
  when: php.packages is defined
  notify:
    - Start PHP7.1-FPM

- include: configure.yml
